#!/usr/bin/env ruby

Dir.chdir File.expand_path(__dir__)

require_relative '../../Base/lib/dotenv'

trial_dir = dotenv_trial_dir(__dir__)

dotenv_trial_data_scripts(__dir__).each do |script|
  system "../../../data/#{script} #{trial_dir}"
end
