#!/usr/bin/env ruby

require_relative '../../Base/lib/base'
require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_data'
require_relative '../../Base/lib/trial_settings'

require 'awesome_print'

puts "EXCHANGE_DIR=#{Exchange.src_dir}"

puts 'EXERCISE SETTINGS'
ap TrialSettings.settings

puts 'LOADING IORA'
require 'iora'

puts 'CLOSE ALL EXISTING IORA ISSUES'
iora = Iora.new(TS.tracker_type, TS.tracker_name)
iora.issues.each do |el|
  iora.close(el['sequence'])
  print '.'
end
puts ''


