#!/usr/bin/env ruby

require_relative '../../Base/lib/base'
require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_data'
require_relative '../../Base/lib/trial_settings'

require 'awesome_print'

puts "EXCHANGE_DIR=#{Exchange.src_dir}"

puts 'EXERCISE SETTINGS'
ap TrialSettings.settings

puts 'LOADING RAILS'
Exchange.load_rails

puts 'RESOLVE ALL EXPIRED/UNRESOLVED CONTRACTS'
Contract.expired.unresolved.each do |contract|
  ContractCmd::Resolve.new(contract).project
  print "."
end
puts ""
