#!/usr/bin/env ruby

require_relative '../lib/base'
require_relative '../lib/trial_data'
require_relative '../lib/trial_settings'

SCRAMBLES   = TrialData.scrambles(1000)
ANSWER_FILE = "./.trial_data/ANSWERS.txt"

def body_base(scramble, level)
  base = "#{scramble.quiz}\n----------"
  hint = "HINT: word starts with '#{scramble.hint(level)}'"
  return base if level == 0
  "#{base}\n\n#{hint}"
end

def write_answer_line(scramble)
  File.open(ANSWER_FILE, 'a') {|f| f.puts scramble.answer_line}
end

def pr_body(scramble, level)
  body_base(scramble, level) + "\n\nAnswer with a pull request"
end

def write_pr_doc(scramble, level)
  write_answer_line(scramble)
  fn = "./.trial_data/#{scramble.quiz_fn(level)}"
  fn = "./doc/#{scramble.quiz_fn(level)}"
  File.open(fn, 'w') {|f| f.puts(comment_body(scramble, level))}
end

def comment_body(scramble, level)
  body_base(scramble, level) + "\n\nAnswer in the issue comments"
end

def write_comment_doc(scramble, level)
  write_answer_line(scramble)
  fn = "./.trial_data/#{scramble.quiz_fn(level)}"
  File.open(fn, 'w') {|f| f.puts(comment_body(scramble, level))}
end

def write_docs(type, numdocs, maxlevel)
  (0..maxlevel).each do |level|
    SCRAMBLES.sample(numdocs).each do |scramble|
      case type
      when :pr      then write_pr_doc(scramble, level)
      when :comment then write_comment_doc(scramble, level)
      end
    end
  end
end

Dir.chdir TS.trial_repo_dir
system "mkdir -p doc"
system "mkdir -p .trial_data"
system "rm -f doc/*.md"
system "rm -f .trial_data/*.md"

write_docs(:pr     , TS.num_pr_issues     , TS.max_hint_level)
write_docs(:comment, TS.num_comment_issues, TS.max_hint_level)
