#!/usr/bin/env ruby

require_relative '../lib/base'
require_relative '../../Base/lib/base'
require_relative '../../Base/lib/trial_settings'
require_relative '../lib/trial_data'

DATA_SRC = TrialData.new
TIMESTAMP = Time.now.strftime("%d%H%M")

Dir.chdir TS.trial_repo_dir
system "mkdir -p Exercise"
system "rm -f Exercise/*html"
Dir.chdir "Exercise"

def fname(idx)
  maxpad = TS.num_exercise_docs.to_s.length
  zpad = idx.to_s.rjust(maxpad, "0")
  "file#{zpad}_#{TIMESTAMP}.html"
end

(0..TS.num_exercise_docs).to_a.each do |idx|
  File.open(fname(idx), "w") {|f| f.puts DATA_SRC.marked_para}
end
