#!/usr/bin/env ruby

require 'securerandom'
require 'iora'

# ----- command line -----

CMD = __FILE__.split("/").last
DIR = File.expand_path(ARGV[0])
USAGE = "Usage: #{CMD} <trial_dir>"

abort USAGE if ARGV.length != 1
abort "#{USAGE}\nERROR: #{ARGV[0]} not a directory" unless File.directory?(DIR)

# ----- filepaths -----

TRIAL_DIR       = DIR
DOC_DIR         = "Scramwords"
ANSWER_FILE     = "./.trial_data/scram_answers.txt"
TASKS_FILE      = "./.trial_data/scram_tasks.yml"
TERMS_FILE      = "./.trial_data/scram_terms.yml"
PAIR_TASKS_FILE = "./.trial_data/scram_pair_tasks.yml"
LCL_SETTINGS    = File.expand_path(__dir__) + "/scram_settings.yml"

puts "TRIAL DIR IS #{TRIAL_DIR}"
puts "DOC DIR IS #{DOC_DIR}"

# ----- settings and libraries -----

puts "COPY SCRAMWORD SETTINGS INTO DIRECTORY #{TRIAL_DIR}/.trial_data"
system "cp #{LCL_SETTINGS} #{TRIAL_DIR}/.trial_data"

require_relative '../../exercise/Base/lib/trial_settings'
require_relative './scram_data'

SCRAMBLES = ScramData.scrambles(1000)

# ----- methods -----

def body_base(scramble, level)
  base = "#{scramble.quiz}\n----------"
  hint = "HINT: word starts with '#{scramble.hint(level)}'"
  return base if level == 0
  "#{base}\n\n#{hint}\n\n"
end

def pair_doc_body(scramble, level)
  instructions = <<~EOF.gsub("\n", " ")
  TO RESOLVE THIS ISSUE: unscramble the word, and add it to the document.
  Then submit a pull-request.  The document URL is:
  EOF
  url = "#{TS.repo_url}/doc/#{scramble.quiz_fn(level)}"
  body_base(scramble, level) + "\n\n#{instructions}\n#{url}"
end

def pair_task_body(scramble, level)
  body_base(scramble, level) + "\n\n /#{SecureRandom.hex(3)} "
end

def task_body(scramble, level)
  instructions = <<~EOF.gsub("\n", " ")
  TO RESOLVE THIS ISSUE: post the unscrambled word
  in the issue comments.
  EOF
  body_base(scramble, level) + "\n\n#{instructions}\n\n /#{SecureRandom.hex(3)} "
end

# ----- writers -----

def write_answer_line(scramble)
  File.open(ANSWER_FILE, 'a') {|f| f.puts scramble.answer_line}
end

def write_pair_doc(scramble, level)
  write_answer_line(scramble)
  fn = "./#{DOC_DIR}/#{scramble.quiz_fn(level)}"
  File.open(fn, 'w') {|f| f.puts(pair_doc_body(scramble, level))}
end

def write_pair_task(scramble, level)
  write_answer_line(scramble)
  File.open(PAIR_TASKS_FILE, 'a') do |f|
    f.puts "- title:  #{scramble.quiz_level(level, 'p')}"
    f.puts "  labels: EXERCISE HINTLEVEL_#{level} RESOLVE_WITH_PR"
    f.puts "  body:   \"#{pair_task_body(scramble, level)}\""
    f.puts ""
  end
end

def write_task(scramble, level)
  write_answer_line(scramble)
  File.open(TASKS_FILE, 'a') do |f|
    f.puts "- title:  #{scramble.quiz_level(level, 't')}"
    f.puts "  labels: EXERCISE HINTLEVEL_#{level} RESOLVE_WITH_COMMENT"
    f.puts "  body:   \"#{task_body(scramble, level)}\""
    f.puts ""
  end
end

# ----- loops -----

def write_pairs(numpairs, maxlevel)
  (0..maxlevel).each do |level|
    SCRAMBLES.sample(numpairs).each do |scramble|
      write_pair_doc(scramble, level)
      write_pair_task(scramble, level)
      print "."
    end
  end
  puts ""
end

def write_tasks(numtasks, maxlevel)
  (0..maxlevel).each do |level|
    SCRAMBLES.sample(numtasks).each do |scramble|
      write_task(scramble, level)
      print "."
    end
  end
  puts ""
end

def write_terms(task_file, term_file)
  tasks = YAML.load_file(task_file)
  File.open(term_file, 'w') do |f|
    f.puts "---"
    tasks.each do |task|
      cat   = task["title"].split("_").last
      hexid = Iora.hexid_for(task)
      f.puts "- price:  #{TS.settings.fetch("scram_#{cat}_price".to_sym, 1.00)}"
      f.puts "  volume: #{TS.settings.fetch("scram_#{cat}_volume".to_sym, 10)}"
      f.puts "  hexid:  #{hexid}"
      print '.'
    end
  end
  puts ''
end

# ----- execution -----

Dir.chdir TS.trial_dir
system "mkdir -p #{DOC_DIR}"
system "rm -f #{DOC_DIR}/*.md"
system "mkdir -p .trial_data"
system "rm -f #{ANSWER_FILE}"
system "echo --- > #{TASKS_FILE}"
system "echo --- > #{PAIR_TASKS_FILE}"

puts "WRITING PAIRS"
write_pairs(TS.scram_num_pairs, TS.scram_max_hint_level)

puts "WRITING TASKS"
write_tasks(TS.scram_num_tasks, TS.scram_max_hint_level)

puts "WRITING TERMS"
write_terms(TASKS_FILE     , TASKS_FILE.gsub("task", "term"))
write_terms(PAIR_TASKS_FILE, PAIR_TASKS_FILE.gsub("task", "term"))
